version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: AslanTest
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
