version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: AslanTest
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  aslan-server:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - '8080:8000'
    volumes:
      - ./:/usr/src/app/
    command: ['sh', '-c', 'sleep 20 && npm run start:dev']
